steps:
  - name: gcr.io/cloud-builders/docker
    id: build
    entrypoint: bash
    args:
      - -c
      - |
        docker build -t gcr.io/citest1/web/citest:cloudbuild citest
        docker push gcr.io/citest1/web/citest:cloudbuild
        docker images --format "{{.Digest}}" gcr.io/citest1/web/citest > digest
  - name: gcr.io/cloud-builders/git
    id: manifest-updete
    entrypoint: /bin/sh
    args:
      - -exc
      - |
        git clone --depth 1 -b master https://tigerfdev:$$PASSWORD@github.com/tigerfdev/ci-test-release.git
        cd ci-test-release
        git config --global user.name "concourse"
        git config --global user.email "concourse@no.reply"
        sed -i -e "s/digest: .*$/digest: $(cat ../digest)/" manifests/citest/kustomize/overlays/cloudbuild/kustomization.yaml
        git add ./manifests/citest/kustomize/overlays/cloudbuild/kustomization.yaml
        if ! git diff-index --quiet HEAD --; then
          git commit -m "CI: update manifests"
        else
          echo "No changes to commit. skipping"
        fi
        git push origin master
    secretEnv: [PASSWORD]
secrets:
  - kmsKeyName: projects/citest1/locations/global/keyRings/citest/cryptoKeys/git-key
    secretEnv:
      PASSWORD: CiQAd2rYPsFokE4cEWQQAHJ/RqWnDfj9JP23+LoEkgdNjHTqSoQSUQDyRViE4HebFT855hNENqzm/2w4KapVmIfcZqoIu2p5fB+KPhlftYldrC41Frm4CEQqjqWiNxeAPpKn3KGyvRc0aOeJzMBMEEXIWO03joi2Pw==