orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
version: 2.1
workflows:
  build_and_push_image:
    jobs:
      - gcp-gcr/build-and-push-image:
          path: citest
          image: web/citest
          registry-url: gcr.io
          tag: circleci