orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
version: 2.1
workflows:
  build_and_push_image:
    jobs:
      - gcp-gcr/build-and-push-image:
          context: citest
          image: citest1/web/citest:cloudbuild
          registry-url: gcr.io
          target-tag: circleci